remote_theme: wowthemesnet/mediumish-theme-jekyll

# Site
name: "Gyulish"
description: "Development story. Discuss mainly about linux kernel, system optimazation and tools. Not only share knowledge of development and system analyzation know-how and also introduce new technology. Awesome!"
meta_description: "Development, Photograph, Dailly life."
logo: 'assets/images/logo.png'
favicon: 'assets/images/logo.png'
baseurl: /
google_analytics: 'UA-115098754-1'
disqus: ''
mailchimp-list: ''

# Authors
authors:
  gyul:
    name: Changhee Han
    display_name: Changhee Han
    gravatar: 
    email: gyulkkajo@gmail.com
    web: http://nophotoplease.tistory.com
    twitter: 
    description: "Changhee Han who is known as gyulkkajo which is a favorite nickname of him. Software developer in Korea. Amateur photographer. Burger lover."

# Plugins
plugins: 
  - jekyll-paginate
  - jekyll-archives
    
# Archives
jekyll-archives:
  enabled:
    - categories
  layout: archive
  permalinks:
    category: '/category/:name/'
    
# Pagination 
paginate: 6
paginate_path: /page:num/
    
# Other
markdown: kramdown
highlighter: rouge
